<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Settings - Color Picker</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-[#0d150d] text-[#EDEDEC] min-h-screen py-8 px-4">
    <div class="max-w-6xl mx-auto">
        <div class="mb-8">
            <h1 class="text-3xl font-bold mb-2">Settings</h1>
            <p class="text-[#A1A09A]">Select a color from the Tailwind CSS v4 palette</p>
        </div>

        @if(session('success'))
            <div class="mb-6 flex items-center gap-3 px-5 py-3 bg-emerald-950 text-[#10b981] rounded-2xl backdrop-blur-sm">
                <svg class="w-5 h-5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
                </svg>
                <span class="text-sm font-medium">{{ session('success') }}</span>
            </div>
        @endif

        <form method="POST" action="{{ route('settings.store') }}" id="colorForm">
            @csrf
            <input type="hidden" name="color" id="selectedColor" value="" required>

            <div class="bg-[#161615] border border-[#3E3E3A] rounded-2xl p-6 mb-6">
                <div class="mb-4">
                    <label class="block text-sm font-medium mb-2">Selected Color</label>
                    <div class="flex items-center gap-4">
                        <div id="colorPreview" class="w-16 h-16 rounded-lg border-2 border-[#3E3E3A] bg-gray-500"></div>
                        <div>
                            <div id="colorHex" class="text-xl font-mono font-semibold text-[#EDEDEC]">#000000</div>
                            <div class="text-sm text-[#A1A09A]">Click a color below to select</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="bg-[#161615] border border-[#3E3E3A] rounded-2xl p-6">
                <h2 class="text-xl font-semibold mb-6">Tailwind CSS v4 Color Palette</h2>
                
                <div id="colorPalette" class="space-y-8">
                    <!-- Colors will be generated by JavaScript -->
                </div>

                <div class="mt-8 pt-6 border-t border-[#3E3E3A]">
                    <button
                        type="submit"
                        id="submitBtn"
                        disabled
                        class="px-6 py-3 bg-[#3E3E3A] text-[#A1A09A] rounded-xl font-medium transition-all duration-150 cursor-not-allowed disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        Save Color
                    </button>
                    <button
                        type="submit"
                        id="submitBtnActive"
                        style="display: none;"
                        class="px-6 py-3 bg-[#10b981] hover:bg-[#059669] text-white rounded-xl font-medium transition-all duration-150 hover:scale-105 active:scale-95 shadow-lg hover:shadow-[#10b981]/50"
                    >
                        Save Color
                    </button>
                </div>
            </div>
        </form>
    </div>

    <script>
        // Tailwind CSS v4 color palette
        const tailwindColors = {
            red: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            orange: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            amber: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            yellow: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            lime: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            green: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            emerald: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            teal: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            cyan: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            sky: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            blue: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            indigo: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            violet: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            purple: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            fuchsia: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            pink: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            rose: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
        };

        // Map of Tailwind class names for reference
        const tailwindClassMap = {
            'red-50': 'bg-red-50', 'red-100': 'bg-red-100', 'red-200': 'bg-red-200', 'red-300': 'bg-red-300', 'red-400': 'bg-red-400', 'red-500': 'bg-red-500', 'red-600': 'bg-red-600', 'red-700': 'bg-red-700', 'red-800': 'bg-red-800', 'red-900': 'bg-red-900', 'red-950': 'bg-red-950',
            'orange-50': 'bg-orange-50', 'orange-100': 'bg-orange-100', 'orange-200': 'bg-orange-200', 'orange-300': 'bg-orange-300', 'orange-400': 'bg-orange-400', 'orange-500': 'bg-orange-500', 'orange-600': 'bg-orange-600', 'orange-700': 'bg-orange-700', 'orange-800': 'bg-orange-800', 'orange-900': 'bg-orange-900', 'orange-950': 'bg-orange-950',
            'amber-50': 'bg-amber-50', 'amber-100': 'bg-amber-100', 'amber-200': 'bg-amber-200', 'amber-300': 'bg-amber-300', 'amber-400': 'bg-amber-400', 'amber-500': 'bg-amber-500', 'amber-600': 'bg-amber-600', 'amber-700': 'bg-amber-700', 'amber-800': 'bg-amber-800', 'amber-900': 'bg-amber-900', 'amber-950': 'bg-amber-950',
            'yellow-50': 'bg-yellow-50', 'yellow-100': 'bg-yellow-100', 'yellow-200': 'bg-yellow-200', 'yellow-300': 'bg-yellow-300', 'yellow-400': 'bg-yellow-400', 'yellow-500': 'bg-yellow-500', 'yellow-600': 'bg-yellow-600', 'yellow-700': 'bg-yellow-700', 'yellow-800': 'bg-yellow-800', 'yellow-900': 'bg-yellow-900', 'yellow-950': 'bg-yellow-950',
            'lime-50': 'bg-lime-50', 'lime-100': 'bg-lime-100', 'lime-200': 'bg-lime-200', 'lime-300': 'bg-lime-300', 'lime-400': 'bg-lime-400', 'lime-500': 'bg-lime-500', 'lime-600': 'bg-lime-600', 'lime-700': 'bg-lime-700', 'lime-800': 'bg-lime-800', 'lime-900': 'bg-lime-900', 'lime-950': 'bg-lime-950',
            'green-50': 'bg-green-50', 'green-100': 'bg-green-100', 'green-200': 'bg-green-200', 'green-300': 'bg-green-300', 'green-400': 'bg-green-400', 'green-500': 'bg-green-500', 'green-600': 'bg-green-600', 'green-700': 'bg-green-700', 'green-800': 'bg-green-800', 'green-900': 'bg-green-900', 'green-950': 'bg-green-950',
            'emerald-50': 'bg-emerald-50', 'emerald-100': 'bg-emerald-100', 'emerald-200': 'bg-emerald-200', 'emerald-300': 'bg-emerald-300', 'emerald-400': 'bg-emerald-400', 'emerald-500': 'bg-emerald-500', 'emerald-600': 'bg-emerald-600', 'emerald-700': 'bg-emerald-700', 'emerald-800': 'bg-emerald-800', 'emerald-900': 'bg-emerald-900', 'emerald-950': 'bg-emerald-950',
            'teal-50': 'bg-teal-50', 'teal-100': 'bg-teal-100', 'teal-200': 'bg-teal-200', 'teal-300': 'bg-teal-300', 'teal-400': 'bg-teal-400', 'teal-500': 'bg-teal-500', 'teal-600': 'bg-teal-600', 'teal-700': 'bg-teal-700', 'teal-800': 'bg-teal-800', 'teal-900': 'bg-teal-900', 'teal-950': 'bg-teal-950',
            'cyan-50': 'bg-cyan-50', 'cyan-100': 'bg-cyan-100', 'cyan-200': 'bg-cyan-200', 'cyan-300': 'bg-cyan-300', 'cyan-400': 'bg-cyan-400', 'cyan-500': 'bg-cyan-500', 'cyan-600': 'bg-cyan-600', 'cyan-700': 'bg-cyan-700', 'cyan-800': 'bg-cyan-800', 'cyan-900': 'bg-cyan-900', 'cyan-950': 'bg-cyan-950',
            'sky-50': 'bg-sky-50', 'sky-100': 'bg-sky-100', 'sky-200': 'bg-sky-200', 'sky-300': 'bg-sky-300', 'sky-400': 'bg-sky-400', 'sky-500': 'bg-sky-500', 'sky-600': 'bg-sky-600', 'sky-700': 'bg-sky-700', 'sky-800': 'bg-sky-800', 'sky-900': 'bg-sky-900', 'sky-950': 'bg-sky-950',
            'blue-50': 'bg-blue-50', 'blue-100': 'bg-blue-100', 'blue-200': 'bg-blue-200', 'blue-300': 'bg-blue-300', 'blue-400': 'bg-blue-400', 'blue-500': 'bg-blue-500', 'blue-600': 'bg-blue-600', 'blue-700': 'bg-blue-700', 'blue-800': 'bg-blue-800', 'blue-900': 'bg-blue-900', 'blue-950': 'bg-blue-950',
            'indigo-50': 'bg-indigo-50', 'indigo-100': 'bg-indigo-100', 'indigo-200': 'bg-indigo-200', 'indigo-300': 'bg-indigo-300', 'indigo-400': 'bg-indigo-400', 'indigo-500': 'bg-indigo-500', 'indigo-600': 'bg-indigo-600', 'indigo-700': 'bg-indigo-700', 'indigo-800': 'bg-indigo-800', 'indigo-900': 'bg-indigo-900', 'indigo-950': 'bg-indigo-950',
            'violet-50': 'bg-violet-50', 'violet-100': 'bg-violet-100', 'violet-200': 'bg-violet-200', 'violet-300': 'bg-violet-300', 'violet-400': 'bg-violet-400', 'violet-500': 'bg-violet-500', 'violet-600': 'bg-violet-600', 'violet-700': 'bg-violet-700', 'violet-800': 'bg-violet-800', 'violet-900': 'bg-violet-900', 'violet-950': 'bg-violet-950',
            'purple-50': 'bg-purple-50', 'purple-100': 'bg-purple-100', 'purple-200': 'bg-purple-200', 'purple-300': 'bg-purple-300', 'purple-400': 'bg-purple-400', 'purple-500': 'bg-purple-500', 'purple-600': 'bg-purple-600', 'purple-700': 'bg-purple-700', 'purple-800': 'bg-purple-800', 'purple-900': 'bg-purple-900', 'purple-950': 'bg-purple-950',
            'fuchsia-50': 'bg-fuchsia-50', 'fuchsia-100': 'bg-fuchsia-100', 'fuchsia-200': 'bg-fuchsia-200', 'fuchsia-300': 'bg-fuchsia-300', 'fuchsia-400': 'bg-fuchsia-400', 'fuchsia-500': 'bg-fuchsia-500', 'fuchsia-600': 'bg-fuchsia-600', 'fuchsia-700': 'bg-fuchsia-700', 'fuchsia-800': 'bg-fuchsia-800', 'fuchsia-900': 'bg-fuchsia-900', 'fuchsia-950': 'bg-fuchsia-950',
            'pink-50': 'bg-pink-50', 'pink-100': 'bg-pink-100', 'pink-200': 'bg-pink-200', 'pink-300': 'bg-pink-300', 'pink-400': 'bg-pink-400', 'pink-500': 'bg-pink-500', 'pink-600': 'bg-pink-600', 'pink-700': 'bg-pink-700', 'pink-800': 'bg-pink-800', 'pink-900': 'bg-pink-900', 'pink-950': 'bg-pink-950',
            'rose-50': 'bg-rose-50', 'rose-100': 'bg-rose-100', 'rose-200': 'bg-rose-200', 'rose-300': 'bg-rose-300', 'rose-400': 'bg-rose-400', 'rose-500': 'bg-rose-500', 'rose-600': 'bg-rose-600', 'rose-700': 'bg-rose-700', 'rose-800': 'bg-rose-800', 'rose-900': 'bg-rose-900', 'rose-950': 'bg-rose-950',
        };

        const paletteContainer = document.getElementById('colorPalette');
        const colorPreview = document.getElementById('colorPreview');
        const colorHex = document.getElementById('colorHex');
        const selectedColorInput = document.getElementById('selectedColor');
        const submitBtn = document.getElementById('submitBtn');
        const submitBtnActive = document.getElementById('submitBtnActive');

        // Function to convert RGB to Hex
        function rgbToHex(r, g, b) {
            return "#" + [r, g, b].map(x => {
                const hex = x.toString(16);
                return hex.length === 1 ? "0" + hex : hex;
            }).join("");
        }

        // Function to get computed color as hex from element (handles oklch, rgb, hex, etc.)
        function getColorHex(element) {
            const computed = window.getComputedStyle(element);
            const bgColor = computed.backgroundColor;
            
            // Use canvas to convert any color format to RGB
            const canvas = document.createElement('canvas');
            canvas.width = 1;
            canvas.height = 1;
            const ctx = canvas.getContext('2d');
            
            // Set the background color on the canvas
            ctx.fillStyle = bgColor;
            ctx.fillRect(0, 0, 1, 1);
            
            // Get the pixel data (RGBA)
            const imageData = ctx.getImageData(0, 0, 1, 1);
            const r = imageData.data[0];
            const g = imageData.data[1];
            const b = imageData.data[2];
            
            return rgbToHex(r, g, b);
        }

        // Generate color palette
        Object.keys(tailwindColors).forEach(colorName => {
            const colorGroup = document.createElement('div');
            colorGroup.className = 'mb-6';
            
            const colorLabel = document.createElement('h3');
            colorLabel.className = 'text-sm font-semibold text-[#A1A09A] mb-3 capitalize';
            colorLabel.textContent = colorName;
            colorGroup.appendChild(colorLabel);

            const colorRow = document.createElement('div');
            colorRow.className = 'flex flex-wrap gap-2';
            
            tailwindColors[colorName].forEach(shade => {
                const colorKey = `${colorName}-${shade}`;
                const colorSwatch = document.createElement('button');
                colorSwatch.type = 'button';
                
                // Use CSS variable directly for background color
                const cssVar = `--color-${colorName}-${shade}`;
                colorSwatch.style.backgroundColor = `var(${cssVar})`;
                colorSwatch.className = 'w-12 h-12 rounded-lg border-2 border-[#3E3E3A] hover:scale-110 hover:border-[#10b981] transition-all duration-150 cursor-pointer';
                colorSwatch.setAttribute('data-color-key', colorKey);
                colorSwatch.setAttribute('data-color-var', cssVar);
                
                colorSwatch.addEventListener('click', function(e) {
                    e.preventDefault();
                    
                    // Get the computed background color (will handle oklch conversion)
                    const hexColor = getColorHex(this);
                    
                    // Update the form input
                    selectedColorInput.value = hexColor;
                    
                    // Update the display
                    colorHex.textContent = hexColor.toUpperCase();
                    colorPreview.style.backgroundColor = hexColor;
                    
                    // Update button state
                    submitBtn.style.display = 'none';
                    submitBtnActive.style.display = 'inline-block';
                    
                    // Remove previous selection
                    document.querySelectorAll('[data-color-key]').forEach(btn => {
                        btn.classList.remove('ring-2', 'ring-[#10b981]', 'ring-offset-2', 'ring-offset-[#161615]');
                    });
                    
                    // Add selection indicator
                    this.classList.add('ring-2', 'ring-[#10b981]', 'ring-offset-2', 'ring-offset-[#161615]');
                });
                
                colorRow.appendChild(colorSwatch);
            });
            
            colorGroup.appendChild(colorRow);
            paletteContainer.appendChild(colorGroup);
        });
    </script>
</body>
</html>

