<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Settings - Color Picker</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-[#0d150d] text-[#EDEDEC] min-h-screen py-8 px-4">
    <div class="max-w-6xl mx-auto">
        <div class="mb-8">
            <h1 class="text-3xl font-bold mb-2">Settings</h1>
            <p class="text-[#A1A09A]">Select a color from the Tailwind CSS v4 palette</p>
        </div>

        @if(session('success'))
            <div class="mb-6 flex items-center gap-3 px-5 py-3 bg-emerald-950 text-[#10b981] rounded-2xl backdrop-blur-sm">
                <svg class="w-5 h-5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
                </svg>
                <span class="text-sm font-medium">{{ session('success') }}</span>
            </div>
        @endif

        <!-- AJAX Message Container -->
        <div id="ajaxMessage" class="mb-6 hidden"></div>

        <form method="POST" action="{{ route('settings.store') }}" id="colorForm">
            @csrf
            <input type="hidden" name="color" id="selectedColor" value="" required>

            <div class="bg-[#161615] border border-[#3E3E3A] rounded-2xl p-6 mb-6">
                <div class="mb-4">
                    <label class="block text-sm font-medium mb-2">Selected Color</label>
                    <div class="flex items-center gap-4">
                        <div id="colorPreview" class="w-16 h-16 rounded-lg border-2 border-[#3E3E3A] bg-gray-500"></div>
                        <div>
                            <div id="colorHex" class="text-xl font-mono font-semibold text-[#EDEDEC]">#000000</div>
                            <div class="text-sm text-[#A1A09A]">Click a color below to select</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="bg-[#161615] border border-[#3E3E3A] rounded-2xl p-6">
                <h2 class="text-xl font-semibold mb-6">Tailwind CSS v4 Color Palette</h2>

                <div id="colorPalette" class="max-w-[700px]">
                    <!-- Colors will be generated by JavaScript -->
                </div>
            </div>
        </form>
    </div>

    <script>
        // Tailwind CSS v4 color palette
        const tailwindColors = {
            red: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            orange: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            amber: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            yellow: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            lime: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            green: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            emerald: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            teal: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            cyan: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            sky: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            blue: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            indigo: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            violet: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            purple: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            fuchsia: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            pink: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
            rose: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950],
        };

        const paletteContainer = document.getElementById('colorPalette');
        const colorPreview = document.getElementById('colorPreview');
        const colorHex = document.getElementById('colorHex');
        const selectedColorInput = document.getElementById('selectedColor');
        const ajaxMessage = document.getElementById('ajaxMessage');
        const csrfToken = document.querySelector('input[name="_token"]').value;

        // Function to convert RGB to Hex
        function rgbToHex(r, g, b) {
            return "#" + [r, g, b].map(x => {
                const hex = x.toString(16);
                return hex.length === 1 ? "0" + hex : hex;
            }).join("");
        }

        // Function to get computed color as hex from element (handles oklch, rgb, hex, etc.)
        function getColorHex(element) {
            const computed = window.getComputedStyle(element);
            const bgColor = computed.backgroundColor;

            // Use canvas to convert any color format to RGB
            const canvas = document.createElement('canvas');
            canvas.width = 1;
            canvas.height = 1;
            const ctx = canvas.getContext('2d');

            // Set the background color on the canvas
            ctx.fillStyle = bgColor;
            ctx.fillRect(0, 0, 1, 1);

            // Get the pixel data (RGBA)
            const imageData = ctx.getImageData(0, 0, 1, 1);
            const r = imageData.data[0];
            const g = imageData.data[1];
            const b = imageData.data[2];

            return rgbToHex(r, g, b);
        }

        // Function to get oklch value from CSS variable
        function getOklchValue(cssVar) {
            const root = getComputedStyle(document.documentElement);
            const value = root.getPropertyValue(cssVar).trim();
            return value || '';
        }

        // Function to show message
        function showMessage(message, type = 'success') {
            ajaxMessage.className = `mb-6 flex items-center gap-3 px-5 py-3 rounded-2xl backdrop-blur-sm ${
                type === 'success' 
                    ? 'bg-emerald-950 text-[#10b981]' 
                    : 'bg-[#161615] border border-red-500/40 text-red-400'
            }`;
            
            const icon = type === 'success' 
                ? '<svg class="w-5 h-5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" /></svg>'
                : '<svg class="w-5 h-5 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" /></svg>';
            
            ajaxMessage.innerHTML = `${icon}<span class="text-sm font-medium">${message}</span>`;
            ajaxMessage.classList.remove('hidden');
            
            // Auto-hide after 5 seconds
            setTimeout(() => {
                ajaxMessage.classList.add('hidden');
            }, 5000);
        }

        // Function to submit color via AJAX
        async function submitColor(hexColor) {
            try {
                const formData = new FormData();
                formData.append('color', hexColor);
                formData.append('_token', csrfToken);

                const response = await fetch('{{ route("settings.store") }}', {
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest'
                    },
                    body: formData
                });

                const data = await response.json();

                if (response.ok) {
                    showMessage(data.message || `Color ${hexColor.toUpperCase()} saved successfully!`, 'success');
                } else {
                    // Handle validation errors
                    let errorMessage = 'Failed to save color';
                    if (data.errors && data.errors.color) {
                        errorMessage = data.errors.color[0];
                    } else if (data.message) {
                        errorMessage = data.message;
                    }
                    showMessage(errorMessage, 'error');
                }
            } catch (error) {
                console.error('Error submitting color:', error);
                showMessage('An error occurred while saving the color. Please try again.', 'error');
            }
        }

        // Add column header row
        const headerRow = document.createElement('div');
        headerRow.className = 'grid grid-cols-[120px_1fr] gap-4 items-center mb-4';
        
        const headerLabel = document.createElement('div');
        headerLabel.className = 'text-sm font-semibold text-[#A1A09A]';
        headerRow.appendChild(headerLabel);
        
        const headerColumns = document.createElement('div');
        headerColumns.className = 'grid grid-cols-11 gap-1.5 sm:gap-4';
        
        const shadeNumbers = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
        shadeNumbers.forEach(shade => {
            const headerCell = document.createElement('div');
            headerCell.className = 'text-xs font-medium text-[#A1A09A] text-center';
            headerCell.textContent = shade;
            headerColumns.appendChild(headerCell);
        });
        
        headerRow.appendChild(headerColumns);
        paletteContainer.appendChild(headerRow);

        // Generate color palette
        Object.keys(tailwindColors).forEach(colorName => {
            const colorGroup = document.createElement('div');
            colorGroup.className = 'grid grid-cols-[120px_1fr] gap-4 items-center mb-6';

            // Color label on the left
            const colorLabel = document.createElement('h3');
            colorLabel.className = 'text-sm font-semibold text-white capitalize';
            colorLabel.textContent = colorName;
            colorGroup.appendChild(colorLabel);

            // Color grid
            const colorRow = document.createElement('div');
            colorRow.className = 'grid grid-cols-11 gap-1.5 sm:gap-4';

            tailwindColors[colorName].forEach(shade => {
                const colorKey = `${colorName}-${shade}`;
                const cssVar = `--color-${colorName}-${shade}`;

                // Container for swatch and popover
                const swatchContainer = document.createElement('div');
                swatchContainer.className = 'relative group';

                const colorSwatch = document.createElement('button');
                colorSwatch.type = 'button';
                colorSwatch.style.backgroundColor = `var(${cssVar})`;
                colorSwatch.className = 'w-full aspect-square rounded-lg hover:scale-110 transition-all duration-150 cursor-pointer';
                colorSwatch.setAttribute('data-color-key', colorKey);
                colorSwatch.setAttribute('data-color-var', cssVar);

                // Popover element
                const popover = document.createElement('div');
                popover.className = 'absolute z-50 invisible opacity-0 group-hover:visible group-hover:opacity-100 bottom-full left-1/2 -translate-x-1/2 mb-2 px-3 py-2 bg-[#161615] border border-[#3E3E3A] rounded-lg shadow-lg whitespace-nowrap transition-opacity duration-150 pointer-events-none';

                // Popover arrow
                const popoverArrow = document.createElement('div');
                popoverArrow.className = 'absolute top-full left-1/2 -translate-x-1/2 -mt-px';
                popoverArrow.innerHTML = '<div class="w-2 h-2 bg-[#161615] border-r border-b border-[#3E3E3A] rotate-45"></div>';

                const popoverContent = document.createElement('div');
                popoverContent.className = 'text-xs space-y-1 relative z-10';

                const hexValue = document.createElement('div');
                hexValue.className = 'text-[#EDEDEC] font-mono';
                hexValue.setAttribute('data-hex', '');

                const oklchValue = document.createElement('div');
                oklchValue.className = 'text-[#A1A09A] font-mono';
                oklchValue.setAttribute('data-oklch', '');

                popoverContent.appendChild(hexValue);
                popoverContent.appendChild(oklchValue);
                popover.appendChild(popoverContent);
                popover.appendChild(popoverArrow);

                // Update popover on hover
                colorSwatch.addEventListener('mouseenter', function() {
                    const hex = getColorHex(this);
                    const oklch = getOklchValue(cssVar);
                    hexValue.textContent = `HEX: ${hex.toUpperCase()}`;
                    oklchValue.textContent = `OKLCH: ${oklch}`;
                });

                colorSwatch.addEventListener('click', function(e) {
                    e.preventDefault();

                    // Get the computed background color (will handle oklch conversion)
                    const hexColor = getColorHex(this);

                    // Update the form input
                    selectedColorInput.value = hexColor;

                    // Update the display
                    colorHex.textContent = hexColor.toUpperCase();
                    colorPreview.style.backgroundColor = hexColor;

                    // Remove previous selection
                    document.querySelectorAll('[data-color-key]').forEach(btn => {
                        btn.classList.remove('ring-2', 'ring-[#10b981]', 'ring-offset-2', 'ring-offset-[#161615]');
                    });

                    // Add selection indicator
                    this.classList.add('ring-2', 'ring-[#10b981]', 'ring-offset-2', 'ring-offset-[#161615]');

                    // Submit via AJAX
                    submitColor(hexColor);
                });

                swatchContainer.appendChild(colorSwatch);
                swatchContainer.appendChild(popover);
                colorRow.appendChild(swatchContainer);
            });

            colorGroup.appendChild(colorRow);
            paletteContainer.appendChild(colorGroup);
        });
    </script>
</body>
</html>

